export const CHANGE_SELECTED = "CHAANGE_SELECTED";
export const CHANGE_INPUT = "CHANGE_INPUT";
export const CHANGE_INPUT_CURRENCY = "CHANGE_INPUT_CURRENCY";
export const CHANGE_OUTPUT = "CHANGE_OUTPUT";
export const CHANGE_OUTPUT_CURRENCY = "CHANGE_OUTPUT_CURRENCY";
export const UPDATE_RATES = "UPDATE_RATES";
export const RECALCULATE_IO = "RECALCULATE_IO";
